version: "3"

services:
  db:
    image: "rethinkdb"
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - "./tmp/rethinkdb:/var/lib/rethinkdb"
  app:
    image: "esa"
    ports:
      - "3001:3001"
