version: "3"

services:
  db:
    image: "rethinkdb"
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - "./rethink:/data"
  app:
    image: "esa"
    ports:
      - "3001:3001"
    volumes:
      - "./templates:/go/src/github.com/esamarathon/website/templates"
