version: "3.7"

services:
  db:
    image: "rethinkdb"
    ports:
      - "8080:8080"
      - "28015:28015"
    volumes:
      - "./rethink:/data:Z"
  app:
    image: "esamarathon/website"
    build: .
    environment:
      - DB_HOST=db:28015
    depends_on:
      - db
    ports:
      - "3001:3001"
    volumes:
      - "./.env:/app/.env"
      - "./templates:/app/templates"
      - "/home/planks/uploaded_files:/app/public/assets/uploads/planks"
